
; RUN: clspv-opt --passes=replace-opencl-builtin %s -o %t.ll
; RUN: FileCheck %s < %t.ll

; AUTO-GENERATED TEST FILE
; This test was generated by add_sat_test_gen.cpp.
; Please modify the that file and regenerate the tests to make changes.

target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

define i8 @add_sat_uchar(i8 %a, i8 %b) {
entry:
 %call = call i8 @_Z7add_sathh(i8 %a, i8 %b)
 ret i8 %call
}

declare i8 @_Z7add_sathh(i8, i8)

; CHECK: [[call:%[a-zA-Z0-9_.]+]] = call { i8, i8 } @_Z8spirv.op.149.hh(i32 149, i8 %a, i8 %b)
; CHECK: [[ex0:%[a-zA-Z0-9_.]+]] = extractvalue { i8, i8 } [[call]], 0
; CHECK: [[ex1:%[a-zA-Z0-9_.]+]] = extractvalue { i8, i8 } [[call]], 1
; CHECK: [[cmp:%[a-zA-Z0-9_.]+]] = icmp eq i8 [[ex1]], 0
; CHECK: [[sel:%[a-zA-Z0-9_.]+]] = select i1 [[cmp]], i8 [[ex0]], i8 -1
; CHECK: ret i8 [[sel]]
