
; RUN: clspv-opt -ReplaceOpenCLBuiltin %s -o %t.ll
; RUN: FileCheck %s < %t.ll

; AUTO-GENERATED TEST FILE
; This test was generated by add_sat_test_gen.cpp.
; Please modify the that file and regenerate the tests to make changes.

target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

define i64 @add_sat_long(i64 %a, i64 %b) {
entry:
 %call = call i64 @_Z7add_satll(i64 %a, i64 %b)
 ret i64 %call
}

declare i64 @_Z7add_satll(i64, i64)

; CHECK: [[add:%[a-zA-Z0-9_.]+]] = add i64 %a, %b
; CHECK: [[a_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i64 %a, 0
; CHECK: [[b_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i64 %b, 0
; CHECK: [[both_neg:%[a-zA-Z0-9_.]+]] = and i1 [[a_lt0]], [[b_lt0]]
; CHECK: [[a_ge0:%[a-zA-Z0-9_.]+]] = xor i1 [[a_lt0]], true
; CHECK: [[b_ge0:%[a-zA-Z0-9_.]+]] = xor i1 [[b_lt0]], true
; CHECK: [[both_pos:%[a-zA-Z0-9_.]+]] = and i1 [[a_ge0]], [[b_ge0]]
; CHECK: [[add_ge0:%[a-zA-Z0-9_.]+]] = icmp sge i64 [[add]], 0
; CHECK: [[add_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i64 [[add]], 0
; CHECK: [[pos_clamp:%[a-zA-Z0-9_.]+]] = select i1 [[add_lt0]], i64 9223372036854775807, i64 [[add]]
; CHECK: [[neg_clamp:%[a-zA-Z0-9_.]+]] = select i1 [[add_ge0]], i64 -9223372036854775808, i64 [[add]]
; CHECK: [[sel:%[a-zA-Z0-9_.]+]] = select i1 [[both_neg]], i64 [[neg_clamp]], i64 [[add]]
; CHECK: [[sel2:%[a-zA-Z0-9_.]+]] = select i1 [[both_pos]], i64 [[pos_clamp]], i64 [[sel]]
; CHECK: ret i64 [[sel2]]
