
; RUN: clspv-opt -ReplaceOpenCLBuiltin %s -o %t.ll
; RUN: FileCheck %s < %t.ll

; AUTO-GENERATED TEST FILE
; This test was generated by add_sat_test_gen.cpp.
; Please modify the that file and regenerate the tests to make changes.

target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

define i32 @add_sat_int(i32 %a, i32 %b) {
entry:
 %call = call i32 @_Z7add_satii(i32 %a, i32 %b)
 ret i32 %call
}

declare i32 @_Z7add_satii(i32, i32)

; CHECK: [[add:%[a-zA-Z0-9_.]+]] = add i32 %a, %b
; CHECK: [[a_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i32 %a, 0
; CHECK: [[b_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i32 %b, 0
; CHECK: [[both_neg:%[a-zA-Z0-9_.]+]] = and i1 [[a_lt0]], [[b_lt0]]
; CHECK: [[a_ge0:%[a-zA-Z0-9_.]+]] = xor i1 [[a_lt0]], true
; CHECK: [[b_ge0:%[a-zA-Z0-9_.]+]] = xor i1 [[b_lt0]], true
; CHECK: [[both_pos:%[a-zA-Z0-9_.]+]] = and i1 [[a_ge0]], [[b_ge0]]
; CHECK: [[add_ge0:%[a-zA-Z0-9_.]+]] = icmp sge i32 [[add]], 0
; CHECK: [[add_lt0:%[a-zA-Z0-9_.]+]] = icmp slt i32 [[add]], 0
; CHECK: [[pos_clamp:%[a-zA-Z0-9_.]+]] = select i1 [[add_lt0]], i32 2147483647, i32 [[add]]
; CHECK: [[neg_clamp:%[a-zA-Z0-9_.]+]] = select i1 [[add_ge0]], i32 -2147483648, i32 [[add]]
; CHECK: [[sel:%[a-zA-Z0-9_.]+]] = select i1 [[both_neg]], i32 [[neg_clamp]], i32 [[add]]
; CHECK: [[sel2:%[a-zA-Z0-9_.]+]] = select i1 [[both_pos]], i32 [[pos_clamp]], i32 [[sel]]
; CHECK: ret i32 [[sel2]]
