namespace clspv {
    namespace Builtins {
        enum EBuiltinType {
            EBuiltinNone                                 =    0,

            EType_Async_Start                            =    1,
            EAsyncWorkGroupCopy                          ,
            EAsyncWorkGroupStridedCopy                   ,
            EWaitGroupEvents                             ,
            EPrefetch                                    ,
            EType_Async_End                              =    6,

            EType_Atomic_Start                           =    7,
            EAtomicInit                                  ,
            EAtomicAdd                                   ,
            EAtomicSub                                   ,
            EAtomicInc                                   ,
            EAtomicDec                                   ,
            EAtomicXchg                                  ,
            EAtomicCmpxchg                               ,
            EAtomicMin                                   ,
            EAtomicMax                                   ,
            EAtomicAnd                                   ,
            EAtomicOr                                    ,
            EAtomicXor                                   ,
            EAtomicWorkItemFence                         ,
            EAtomicStore                                 ,
            EAtomicStoreExplicit                         ,
            EAtomicLoad                                  ,
            EAtomicLoadExplicit                          ,
            EAtomicExchange                              ,
            EAtomicExchangeExplicit                      ,
            EAtomicCompareExchangeStrong                 ,
            EAtomicCompareExchangeStrongExplicit         ,
            EAtomicCompareExchangeWeak                   ,
            EAtomicCompareExchangeWeakExplicit           ,
            EAtomicFetchKey                              ,
            EAtomicFetchKeyExplicit                      ,
            EAtomicFlagTestAndSet                        ,
            EAtomicFlagTestAndSetExplicit                ,
            EAtomicFlagClear                             ,
            EAtomicFlagClearExplicit                     ,
            EType_Atomic_End                             =   37,

            EType_Common_Start                           =   38,
            EDegrees                                     ,
            EMix                                         ,
            ERadians                                     ,
            ESign                                        ,
            ESmoothstep                                  ,
            EStep                                        ,
            EType_Common_End                             =   45,

            EType_Convert_Start                          =   46,
            EConvert                                     ,
            EType_Convert_End                            =   48,

            EType_Event_Start                            =   49,
            ERetainEvent                                 ,
            EReleaseEvent                                ,
            ECreateUserEvent                             ,
            EIsValidEvent                                ,
            ESetUserEventStatus                          ,
            EType_Event_End                              =   55,

            EType_MemoryFence_Start                      =   56,
            EMemFence                                    ,
            EReadMemFence                                ,
            EWriteMemFence                               ,
            EType_MemoryFence_End                        =   60,

            EType_Geometric_Start                        =   61,
            ECross                                       ,
            EDot                                         ,
            EDistance                                    ,
            ELength                                      ,
            ENormalize                                   ,
            EFastDistance                                ,
            EFastLength                                  ,
            EFastNormalize                               ,
            EType_Geometric_End                          =   70,

            EType_Image_Start                            =   71,
            EReadImagef                                  ,
            EReadImagei                                  ,
            EReadImageui                                 ,
            EReadImageh                                  ,
            EWriteImagef                                 ,
            EWriteImagei                                 ,
            EWriteImageui                                ,
            EWriteImageh                                 ,
            EGetImageWidth                               ,
            EGetImageHeight                              ,
            EGetImageDepth                               ,
            EGetImageChannelDataType                     ,
            EGetImageChannelOrder                        ,
            EGetImageDim                                 ,
            EGetImageArraySize                           ,
            EGetImageNumSamples                          ,
            EType_Image_End                              =   88,

            EType_Integer_Start                          =   89,
            EAbs                                         ,
            EAbsDiff                                     ,
            EAddSat                                      ,
            EClamp                                       ,
            EClz                                         ,
            ECtz                                         ,
            EHadd                                        ,
            EMad24                                       ,
            EMadHi                                       ,
            EMadSat                                      ,
            EMax                                         ,
            EMin                                         ,
            EMul24                                       ,
            EMulHi                                       ,
            EPopcount                                    ,
            ERhadd                                       ,
            ERotate                                      ,
            ESubSat                                      ,
            EUpsample                                    ,
            EType_Integer_End                            =  109,

            EType_Math_Start                             =  110,
            EAcos                                        ,
            EAcosh                                       ,
            EAcospi                                      ,
            EAsin                                        ,
            EAsinh                                       ,
            EAsinpi                                      ,
            EAtan                                        ,
            EAtan2                                       ,
            EAtanh                                       ,
            EAtanpi                                      ,
            EAtan2pi                                     ,
            ECbrt                                        ,
            ECeil                                        ,
            ECopysign                                    ,
            ECos                                         ,
            EHalfCos                                     ,
            ENativeCos                                   ,
            ECosh                                        ,
            ECospi                                       ,
            EHalfDivide                                  ,
            ENativeDivide                                ,
            EErf                                         ,
            EErfc                                        ,
            EExp                                         ,
            EHalfExp                                     ,
            ENativeExp                                   ,
            EExp2                                        ,
            EHalfExp2                                    ,
            ENativeExp2                                  ,
            EExp10                                       ,
            EHalfExp10                                   ,
            ENativeExp10                                 ,
            EExpm1                                       ,
            EFabs                                        ,
            EFdim                                        ,
            EFloor                                       ,
            EFma                                         ,
            EFmax                                        ,
            EFmin                                        ,
            EFmod                                        ,
            EFract                                       ,
            EFrexp                                       ,
            EHypot                                       ,
            EIlogb                                       ,
            ELdexp                                       ,
            ELgamma                                      ,
            ELgammaR                                     ,
            ELog                                         ,
            EHalfLog                                     ,
            ENativeLog                                   ,
            ELog2                                        ,
            EHalfLog2                                    ,
            ENativeLog2                                  ,
            ELog10                                       ,
            EHalfLog10                                   ,
            ENativeLog10                                 ,
            ELog1p                                       ,
            ELogb                                        ,
            EMad                                         ,
            EMagmax                                      ,
            EMagmin                                      ,
            EModf                                        ,
            ENan                                         ,
            ENextafter                                   ,
            EPow                                         ,
            EPown                                        ,
            EPowr                                        ,
            EHalfPowr                                    ,
            ENativePowr                                  ,
            EHalfRecip                                   ,
            ENativeRecip                                 ,
            ERemainder                                   ,
            ERemquo                                      ,
            ERint                                        ,
            ERound                                       ,
            ERootn                                       ,
            ERsqrt                                       ,
            EHalfRsqrt                                   ,
            ENativeRsqrt                                 ,
            ESin                                         ,
            EHalfSin                                     ,
            ENativeSin                                   ,
            ESincos                                      ,
            ESinh                                        ,
            ESinpi                                       ,
            ESqrt                                        ,
            EHalfSqrt                                    ,
            ENativeSqrt                                  ,
            ETan                                         ,
            EHalfTan                                     ,
            ENativeTan                                   ,
            ETanh                                        ,
            ETanpi                                       ,
            ETgamma                                      ,
            ETrunc                                       ,
            EType_Math_End                               =  206,

            EType_Relational_Start                       =  207,
            EIsequal                                     ,
            EIsnotequal                                  ,
            EIsgreater                                   ,
            EIsgreaterequal                              ,
            EIsless                                      ,
            EIslessequal                                 ,
            EIslessgreater                               ,
            EIsfinite                                    ,
            EIsinf                                       ,
            EIsnan                                       ,
            EIsnormal                                    ,
            EIsordered                                   ,
            EIsunordered                                 ,
            ESignbit                                     ,
            EAny                                         ,
            EAll                                         ,
            EBitselect                                   ,
            ESelect                                      ,
            EType_Relational_End                         =  226,

            EType_Sync_Start                             =  227,
            EBarrier                                     ,
            EWorkGroupBarrier                            ,
            EType_Sync_End                               =  230,

            EType_Vector_Start                           =  231,
            EShuffle                                     ,
            EShuffle2                                    ,
            EVecStep                                     ,
            EVload                                       ,
            EVloadHalf                                   ,
            EVloadaHalf                                  ,
            EVstore                                      ,
            EVstoreHalf                                  ,
            EVstoreaHalf                                 ,
            EType_Vector_End                             =  241,

            EType_WorkItem_Start                         =  242,
            EGetGlobalId                                 ,
            EGetGlobalSize                               ,
            EGetGlobalOffset                             ,
            EGetGlobalLinearId                           ,
            EGetGroupId                                  ,
            EGetLocalId                                  ,
            EGetLocalLinearId                            ,
            EGetLocalSize                                ,
            EGetEnqueuedLocalSize                        ,
            EGetNumGroups                                ,
            EGetWorkDim                                  ,
            EType_WorkItem_End                           =  254,

            EType_Pipe_Start                             =  255,
            EReadPipe                                    ,
            EWritePipe                                   ,
            EReserveReadPipe                             ,
            ECommitReadPipe                              ,
            EIsValidReserveId                            ,
            EWorkGroupReserveReadPipe                    ,
            EWorkGroupReserveWritePipe                   ,
            EWorkGroupCommitReadPipe                     ,
            EWorkGroupCommitWritePipe                    ,
            EGetPipeNumPackets                           ,
            EGetPipeMaxPackets                           ,
            EType_Pipe_End                               =  267,

            EType_SubgroupsKHR_Start                     =  268,
            EGetSubGroupSize                             ,
            EGetMaxSubGroupSize                          ,
            EGetNumSubGroups                             ,
            EGetEnqueuedNumSubGroups                     ,
            EGetSubGroupId                               ,
            EGetSubGroupLocalId                          ,
            ESubGroupBarrier                             ,
            ESubGroupAll                                 ,
            ESubGroupAny                                 ,
            ESubGroupBroadcast                           ,
            ESubGroupReduceAdd                           ,
            ESubGroupReduceMin                           ,
            ESubGroupReduceMax                           ,
            ESubGroupScanExclusiveAdd                    ,
            ESubGroupScanExclusiveMin                    ,
            ESubGroupScanExclusiveMax                    ,
            ESubGroupScanInclusiveAdd                    ,
            ESubGroupScanInclusiveMin                    ,
            ESubGroupScanInclusiveMax                    ,
            ESubGroupReserveReadPipe                     ,
            ESubGroupReserveWritePipe                    ,
            ESubGroupCommitReadPipe                      ,
            ESubGroupCommitWritePipe                     ,
            EGetKernelSubGroupCountForNdrange            ,
            EGetKernelMaxSubGroupSizeForNdrange          ,
            EType_SubgroupsKHR_End                       =  294,
        }; // enum EBuiltinType
    } // namespace Builtins
} // namespace clspv

