
; RUN: clspv-opt -ReplaceOpenCLBuiltin -hack-clamp-width %s -o %t.ll
; RUN: FileCheck %s < %t.ll

; AUTO-GENERATED TEST FILE
; This test was generated by mad_sat_test_gen.cpp.
; Please modify the that file and regenerate the tests to make changes.

target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir-unknown-unknown"

define i8 @mad_sat_char(i8 %a, i8 %b, i8 %c) {
entry:
 %call = call i8 @_Z7mad_satccc(i8 %a, i8 %b, i8 %c)
 ret i8 %call
}

declare i8 @_Z7mad_satccc(i8, i8, i8)

; CHECK: [[sext_a:%[a-zA-Z0-9_.]+]] = sext i8 %a to i32
; CHECK: [[sext_b:%[a-zA-Z0-9_.]+]] = sext i8 %b to i32
; CHECK: [[sext_c:%[a-zA-Z0-9_.]+]] = sext i8 %c to i32
; CHECK: [[mul:%[a-zA-Z0-9_.]+]] = mul nuw nsw i32 [[sext_a]], [[sext_b]]
; CHECK: [[add:%[a-zA-Z0-9_.]+]] = add nuw nsw i32 [[mul]], [[sext_c]]
; CHECK: [[clamp:%[a-zA-Z0-9_.]+]] = call i32 @_Z5clampiii(i32 [[add]], i32 -128, i32 127)
; CHECK: [[trunc:%[a-zA-Z0-9_.]+]] = trunc i32 [[clamp]] to i8
; CHECK: ret i8 [[trunc]]
